name: Discord Notifier
description: Get notification on discord.
branding:
  color: black
  icon: message-square

inputs:
  webhook:
    description: A full discord webhook url
    required: true
  message-title:
    description: Message title
    required: false
  thread-id:
    description: Discord thread or forum post ID to send the message into
    required: false

outputs:
  result:
    description: Webhook result
    value: ${{ steps.run.outputs.result }}

runs:
  using: node20
  main: dist/index.js